module.exports = {
    staff_refer: {
        city: {
            colIndex: 9,
            rowIndex: 2,
            fields: [
                {index: 1, field: 'dict_name'}
            ]
        },
        district: {
            colIndex: 11,
            rowIndex: 2,
            fields: [
                {index: 1, field: 'dict_name'}
            ]
        },
        ward: {
            colIndex: 13,
            rowIndex: 2,
            fields: [
                {index: 1, field: 'dict_name'}
            ]
        }
    },
    start_index: 10,
    staff_import_dto: {
        findKey: function (index) {
            return this.mapping.find(e => e.index === index);
        },
        mapping: [
            {index: 1, key: 'index'},
            {index: 2, key: 'staff_id'},
            {index: 3, key: 'name'},
            {index: 4, key: 'date_of_employment'},
            {index: 5, key: 'date_of_birth'},
            {index: 6, key: 'gender'},
            {index: 7, key: 'marital_status'},
            {index: 8, key: 'citizen_id_no'},
            {index: 9, key: 'date_of_issue'},
            {index: 10, key: 'place_of_issue'},
            {index: 11, key: 'nationality'},
            {index: 12, key: 'ethnic'},
            {index: 13, key: 'religion'},
            {index: 14, key: 'graduated'},
            {index: 15, key: 'business_email'},
            {index: 16, key: 'private_email'},
            {index: 17, key: 'mobile_phone'},
            {index: 18, key: 'ext'},
            {index: 19, key: 'country_of_origin_nation'},
            {index: 20, key: 'country_of_origin_province'},
            {index: 21, key: 'country_of_origin_district'},
            {index: 22, key: 'country_of_origin_village'},
            {index: 23, key: 'permanent_address_nation'},
            {index: 24, key: 'permanent_address_province'},
            {index: 25, key: 'permanent_address_district'},
            {index: 26, key: 'permanent_address_village'},
            {index: 27, key: 'permanent_address_detail'},
            {index: 28, key: 'contact_address_nation'},
            {index: 29, key: 'contact_address_province'},
            {index: 30, key: 'contact_address_district'},
            {index: 31, key: 'contact_address_village'},
            {index: 32, key: 'contact_address_detail'},
            {index: 33, key: 'pit_tax_code'},
            {index: 34, key: 'social_insurance_cod'},
            {index: 35, key: 'health_check_book_no'},
            {index: 36, key: 'work_permit_no'},
            {index: 37, key: 'work_permit_title'},
            {index: 38, key: 'work_permit_start_date'},
            {index: 39, key: 'work_permit_end_date'},
            {index: 40, key: 'contact_for_emergency'},
            {index: 41, key: 'emergency_contact_address'},
            {index: 42, key: 'emergency_contact_number'},
        ],
        fake: {
            index: '1',
            staff_id: '2',
            name: '3',
            date_of_employment: '21/02/2022',
            date_of_birth: '5',
            gender: 'gender',
            marital_status: 'Độc thân',
            citizen_id_no: 'citizen_id_no',
            date_of_issue: '21/02/2022',
            place_of_issue: 'place_of_issue',
            nationality: 'Việt Nam',
            ethnic: 'ethnic',
            religion: 'religion',
            graduated: 'graduated',
            business_email: 'business_email',
            private_email: 'private_email',
            mobile_phone: 'mobile_phone',
            ext: 'ext',
            country_of_origin_nation: 'country_of_origin_nation',
            country_of_origin_province: 'country_of_origin_province',
            country_of_origin_district: 'country_of_origin_district',
            country_of_origin_village: 'Dịch Vọng',
            permanent_address_nation: 'permanent_address_nation',
            permanent_address_province: 'permanent_address_province',
            permanent_address_district: 'permanent_address_district',
            permanent_address_village: 'Dịch Vọng',
            permanent_address_detail: 'permanent_address_detail',
            contact_address_nation: 'contact_address_nation',
            contact_address_province: 'contact_address_province',
            contact_address_district: 'contact_address_district',
            contact_address_village: 'Dịch Vọng',
            contact_address_detail: 'contact_address_detail',
            pit_tax_code: 'pit_tax_code',
            social_insurance_cod: 'social_insurance_cod',
            health_check_book_no: 'health_check_book_no',
            work_permit_no: 'work_permit_no',
            work_permit_title: 'work_permit_title',
            work_permit_start_date: 'work_permit_start_date',
            work_permit_end_date: 'work_permit_end_date',
            contact_for_emergency: 'contact_for_emergency',
            emergency_contact_address: 'emergency_contact_address'
        }
    },
    fields: ['id', 'staff_id', 'name', 'date_of_employment', 'date_of_birth', 'gender', 'citizen_id_no', 'date_of_issue', 
        'place_of_issue', 'marital_status', 'country_of_origin', 'nationality', 'ethnic', 'religion', 'graduated', 'business_email', 
        'private_email', 'mobile_phone', 'ext', 'contact_for_emergency', 'emergency_contact_address', 'permanent_address', 
        'permanent_address_detail', 'contact_address', 'contact_address_detail', 'pit_tax_code', 'social_insurance_cod', 
        'work_permit_no', 'work_permit_start_date', 'work_permit_end_date', 'is_active', 'created_time', 'created_by', 
        'updated_by', 'updated_time', 'emergency_contact_number', 'health_check_book_no', 'work_permit_title', 
        'end_date_of_employment'],
    update_key: ['id'],
    mapping: [
        {index: 1, field: 'index'},
        {index: 2, field: 'staff_id'},
        {index: 3, field: 'name'},
        {index: 4, field: 'date_of_employment'},
        {index: 5, field: 'date_of_birth'},
        {index: 6, field: 'gender'},
        {index: 7, field: 'marital_status'},
        {index: 8, field: 'citizen_id_no'},
        {index: 9, field: 'date_of_issue'},
        {index: 10, field: 'place_of_issue'},
        {index: 11, field: 'nationality'},
        {index: 12, field: 'ethnic'},
        {index: 13, field: 'religion'},
        {index: 14, field: 'graduated'},
        {index: 15, field: 'business_email'},
        {index: 16, field: 'private_email'},
        {index: 17, field: 'mobile_phone'},
        {index: 18, field: 'ext'},
        {index: 19, field: 'country_of_origin_nation'},
        {index: 20, field: 'country_of_origin_province'},
        {index: 21, field: 'country_of_origin_district'},
        {index: 22, field: 'country_of_origin_village'},
        {index: 23, field: 'permanent_address_nation'},
        {index: 24, field: 'permanent_address_province'},
        {index: 25, field: 'permanent_address_district'},
        {index: 26, field: 'permanent_address_village'},
        {index: 27, field: 'permanent_address_detail'},
        {index: 28, field: 'contact_address_nation'},
        {index: 29, field: 'contact_address_province'},
        {index: 30, field: 'contact_address_district'},
        {index: 31, field: 'contact_address_village'},
        {index: 32, field: 'contact_address_detail'},
        {index: 33, field: 'pit_tax_code'},
        {index: 34, field: 'social_insurance_cod'},
        {index: 35, field: 'health_check_book_no'},
        {index: 36, field: 'work_permit_no'},
        {index: 37, field: 'work_permit_title'},
        {index: 38, field: 'work_permit_start_date'},
        {index: 39, field: 'work_permit_end_date'},
        {index: 40, field: 'contact_for_emergency'},
        {index: 41, field: 'emergency_contact_address'},
        {index: 42, field: 'emergency_contact_number'},
    ],
    result: {
        index: 43,
        field: 'result'
    }
}
